### ISSUE TITLE
KeyError when attempting to open the NavBar

### ISSUE THREAD

**Issue by DeeeeLAN** [TheClams/SystemVerilog#11]
Somebody I work with started seeing this error this week when attempting to open the NavBar, and it no longer opens: 
```
Traceback (most recent call last):
  File "/home/users/student39/.config/sublime-text-3/Installed Packages/SystemVerilog.sublime-package/verilog_navigation.py", line 971, in <lambda>
  File "/home/users/student39/.config/sublime-text-3/Installed Packages/SystemVerilog.sublime-package/verilog_navigation.py", line 1063, in showHierarchy
  File "/home/users/student39/.config/sublime-text-3/Installed Packages/SystemVerilog.sublime-package/verilog_navigation.py", line 1114, in printContent
KeyError: 'array'
```

**Comment by TheClams** [comment]
Fixed in 2.23.13
