### ISSUE TITLE
KeyError when attempting to open the navbar

### ISSUE THREAD

**Issue by DeeeeLAN** [TheClams/SystemVerilog#8]
I get the following error:

```
Traceback (most recent call last):
  File "/home/users/student98/.config/sublime-text-3/Installed Packages/SystemVerilog.sublime-package/verilog_navigation.py", line 968, in <lambda>
  File "/home/users/student98/.config/sublime-text-3/Installed Packages/SystemVerilog.sublime-package/verilog_navigation.py", line 1060, in showHierarchy
  File "/home/users/student98/.config/sublime-text-3/Installed Packages/SystemVerilog.sublime-package/verilog_navigation.py", line 1105, in printContent
KeyError: 'bw'
```

And the navbar is empty, as it stops loading after that. Repeated opening and closing the navbar produces the same error. 

It is only happening with one project.

**Comment by TheClams** [comment]
Should be fixed in latest version (2.23.9)
